spring:
  profiles:
    active: @profiles.active@
  # 数据库配置
  datasource:
    # hikari连接池配置
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 连接池名称，默认HikariPool-1
      pool-name: HikariPool-1
      # 最大连接数，小于等于0会被重置为默认值10，大于零小于1会被重置为minimum-idle的值，理论上应等于数据库服务器的线程数
      maximum-pool-size: 4
      # 连接超时时间，单位为毫秒，小于250毫秒，会被重置为默认值30秒
      connection-timeout: 60000
      # 最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 1
      # 空闲连接超时时间，单位为毫秒，默认值600000（10分钟），大于max-lifetime+1秒且max-lifetime>0，会被重置为0，不等于0且小于10秒，会被重置为10秒，
      # 只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
      idle-timeout: 600000
      # 连接最大存活时间，单位为毫秒，不等于0且不小于30秒，否则会被重置为默认值30分钟。设置应比数据库超时时间短
      max-lifetime: 1200000
  # redis配置
  redis:
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 4
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 500ms
        # 连接池中的最大空闲连接
        max-idle: 4
        # 连接池中的最小空闲连接
        min-idle: 1
    # 连接超时时间
    timeout: 1s
  # session配置
  session:
    store-type: redis
  # jpa配置
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: error

---
######################################## dev ########################################
server:
  port: 8011
spring:
  profiles: dev
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.140:3306/file_home?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123@Dch_
  # redis配置
  redis:
    host: 192.168.0.140
    port: 6379
    password:
logging:
  config: classpath:logback-dev.xml

---
######################################## prod ########################################
server:
  port: 8011
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.140:3306/file_home?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123@Dch_
  # redis配置
  redis:
    host: 192.168.0.140
    port: 6379
    password:
logging:
  config: classpath:logback-prod.xml